### ISSUE TITLE
Setting elements for trace theme

### ISSUE THREAD

**Issue by Degoot-AM** [epiverse-trace/tracetheme#7]
Proposed specifications for trace theme:
1. Background: White
2. Font: Roboto Mono (applies to all plot elements, including title, labels, axes, legends, etc.)
3. Title: Size = 15, Face = Bold
4. Axes Title (for X and Y): Size = 10, Face = Normal
5. Axis Text (X): Size = 8, Angle = 60
6. Axis Text (Y): Size = 8, Angle = 0
7. Grids (Major and Minor): Color = Black, Size = 0.05
8. Color Scale: Warm Gray

**Comment by rozeggo** [comment]
@Degoot-AM Is it possible to post what this would look like?

**Comment by Degoot-AM** [comment]
Yes, I will provide examples today.

**Comment by Degoot-AM** [comment]
Some examples.. ..!  ![simple_scatter_plot](https://github.com/epiverse-trace/tracetheme/assets/19929487/0d438c71-2ce5-44ce-96fc-c721c53e0068)
![simple_line_plot](https://github.com/epiverse-trace/tracetheme/assets/19929487/62d90526-e2e2-4076-9894-b5f570667c72)
![simple_line2_plot](https://github.com/epiverse-trace/tracetheme/assets/19929487/43dc27aa-ecc3-4d1e-b2b7-f6eae080cdcb)
![simple_bar_plot](https://github.com/epiverse-trace/tracetheme/assets/19929487/1dbd9372-2b0e-425c-9b77-dee7b07a45b9)

**Comment by Bisaloo** [comment]
It looks good to me overall. Or at least, I don't have reasons to prefer alternatives over it. Two minor requests for change:

- the websites use "DM Sans". Can you try using this font so that font on plots and text is matched?
- I believe rotated text is harder to read and would recommend we keep it horizontal as much as possible. If text ever overlaps, it is the sign that either:
  - the figure needs to be exported at a larger size
  - fewer axes breaks need to labelled
  - the axes need to be switched. See the relevant "5. Axes" section in the house rules draft document 

And one question: following @Juanmontenegro99's comment in #4, did you export these plots with the recommended image sizes we are discussing?
